version: '3.9'

networks:
    erp-app:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "7000:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        depends_on:
            - php
            - mysql
        networks:
            - erp-app

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4036:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        env_file: .env
        networks:
            - erp-app

    php:
        image: php:8-fpm
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - erp-app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - erp-app
